New GC sectors
lennycolton/vatglasses-data pull request #127
Opened 2023-10-01 15:15 UTC by rpuig2001

2023-10-01 20:58 UTC, lennycolton commented
Hi, could you please remove all the sectors from neighbouring FIRs?

2023-10-01 20:59 UTC, lennycolton requested changes
Hi, could you please remove all the sectors from neighbouring FIRs?

2023-10-03 11:42 UTC, rpuig2001 commented
What can we do to fix?

2023-10-03 11:59 UTC, lennycolton approved these changes

2023-10-03 11:59 UTC, merged